### ISSUE TITLE
Explore fixes for error in issue_comments - ValueError: invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by ericboucher** [MeltanoLabs/tap-github#128]
Investigate a bit more why the issues/comment is raising the following error `ValueError: invalid literal for int() with base 16: b''`

eg.

<img width="1027" alt="Screen Shot 2022-05-19 at 1 05 17 AM" src="https://user-images.githubusercontent.com/16843267/169212126-23f2a0df-d2ed-4eb5-ac3a-9b5ec2450768.png">

Possible solutions to explore, patching urllib3: https://github.com/psf/requests/issues/4248

**Comment by ericboucher** [comment]
I was able to reproduce the server error on issue/comments directly with:

https://api.github.com/repos/hashicorp/terraform-provider-aws/issues/comments?sort=updated&direction=asc&since=2020-06-22T11:30&per_page=100

The problem I think is that the since parameter is too expensive for large repos. I see two primary options:
1. Act as if the since parameter does not work and paginate in descending order with an early stop instead
2. Try to use a graphql request instead

@laurentS wdyt?

**Comment by laurentS** [comment]
> The problem I think is that the since parameter is too expensive for large repos. I see two primary options:
> 
>     1. Act as if the since parameter does not work and paginate in descending order with an early stop instead
> 
>     2. Try to use a graphql request instead

Option 3. Switch to a different REST endpoint that lists comments for a single issue, as opposed to the entire repo. This would be more "quota hungry" on the `core` quota, so graphql is likely a better option there, if it works.

I'd try whichever is the least work between the 2 options you suggest, and see if it works. This is not properly documented on their side, so short of trying, we probably won't know.
