### ISSUE TITLE
Field `commit_timestamp` may be missing from stream

### ISSUE THREAD

**Issue by edgarrmondragon** [MeltanoLabs/tap-github#166]
The `commit_timetstamp` in the `commits` stream, defined here

https://github.com/MeltanoLabs/tap-github/blob/a0d581e4e425c0e3e2a4d46176080cf9548ddb8b/tap_github/repository_streams.py#L1011

may be missing in some cases.

Reporting by a user in Slack: https://meltano.slack.com/archives/CMN8HELB0/p1668434231067549?thread_ts=1668432453.080249&cid=CMN8HELB0

<details><summary>Screenshot provided by user</summary>
<img width="2390" alt="Снимок экрана 2022-11-14 в 14 56 43" src="https://user-images.githubusercontent.com/16805946/201730242-c910b6ec-354a-4314-a657-cb6996c6b1b8.png">
</details>

**Comment by ericboucher** [comment]
That's not how I understand this error message. Otherwise we would have a KeyError for `date` instead, no?
Could it be that they need to add `commit_timestamp` to the select part of their config?

**Comment by edgarrmondragon** [comment]
@ericboucher IIUC the tap is failing to extract the replication key from the record in this line: https://github.com/meltano/sdk/blob/3cdb614fbb4dcb9874800f23a410efd33111d24c/singer_sdk/helpers/_state.py#L220

```python
    new_rk_value = to_json_compatible(latest_record[replication_key])
```

and that's before the catalog is applied to the record.

**Comment by ericboucher** [comment]
I see, but the  `post_process` would fail otherwise, that's why I'm confused. Is the latest_record not looking at the post_processed entity?

**Comment by edgarrmondragon** [comment]
@ericboucher I think you're right. The replication value is extracted after `post_process`, which makes sense. And, I just noticed the `select` array missing `commits.commit_timetstamp` 🤦‍♂️.

Sorry for the noise!
