### ISSUE TITLE
The "issues" stream is only fetching OPEN issues (and PRs)

### ISSUE THREAD

**Issue by ericboucher** [MeltanoLabs/tap-github#17]
I am interested in puling CLOSED issues and MERGED PRs as well as OPEN ones. The current behavior for the `issues` stream is to pull all OPEN issues (and PRs).

1. I think that by default, the `issues` stream could fetch ALL issues that have been updated since our start date; and we could have an option to only select OPEN issues.

2. Somewhat linked: it could be an opportunity to clearly separate issues and PRs. The issues stream would pull only issues, and a pull_request stream would handle pull_requests.

What do you think?

**Comment by aaronsteers** [comment]
Hi, @ericboucher. Regarding your two points...

> I think that by default, the issues stream could fetch ALL issues that have been updated since our start date; and we could have an option to only select OPEN issues.

100% agreed. I wasn't aware we were missing closed issues/PRs and if true, we should probably treat this as a bug. Happy to review a PR on this if you have any cycles to contribute.

> Somewhat linked: it could be an opportunity to clearly separate issues and PRs. The issues stream would pull only issues, and a pull_request stream would handle pull_requests.

Can you say more about your proposal to have the two distinct streams? My understanding (could be wrong) is that GitHub treats all PRs as issues. Happy to add a stream for PRs if there's a dedicated endpoint for them but I'm not sure it that would lead to removal of them from the Issues sreams.

**Comment by aaronsteers** [comment]
Completed in #21 

🎉
