### ISSUE TITLE
Releases stream has 10,000 record limit

### ISSUE THREAD

**Issue by scottmtp** [MeltanoLabs/tap-github#182]
While trying to extract Releases data from a large private repo, I encountered this error:
`singer_sdk.exceptions.FatalAPIError: 422 Client Error: b'{"message":"Only the first 10000 results are available.","documentation_url":"https://docs.github.com/rest/reference/repos#list-releases"}'`

I was able to work around the issue by forking the repo and setting `MAX_RESULTS_LIMIT = 10000` in ReleasesStream.

**Comment by ericboucher** [comment]
Another great catch @scottmtp. We'll happily merge a PR with that change or include this in our next one.

**Comment by ericboucher** [comment]
To test this, do you happen to know a repo with over 10,000 releases?

**Comment by scottmtp** [comment]
No, I looked around a bit, but couldn't find any public repos with that many releases.
