### ISSUE TITLE
The 'pull_number' field not being populated for the 'pull_request_commits' stream

### ISSUE THREAD

**Issue by scottmtp** [MeltanoLabs/tap-github#183]
The 'pull_number' field not being populated for the 'pull_request_commits' stream.

When I run:
`meltano --log-level=debug run tap-github target-postgres`

In the log output I can see that the  pull_request_commits.pull_number field is selected, and the pull number appears in the context in the `Beginning full_table sync of 'pull_request_commits' with context:` line.

The `RECORD` log lines for pull_request_commits contain the other parent keys (org, repo, repo_id), but not pull_number.

**Comment by scottmtp** [comment]
I'm able to work around this with this change:
```
diff --git a/tap_github/repository_streams.py b/tap_github/repository_streams.py
index e80c4f1..0701250 100644
--- a/tap_github/repository_streams.py
+++ b/tap_github/repository_streams.py
@@ -1351,6 +1351,10 @@ class PullRequestCommits(GitHubRestStream):
         ),
     ).to_dict()
 
+    def post_process(self, row: dict, context: Optional[Dict[str, str]] = None) -> dict:
+        if context is not None and "pull_number" in context:
+            row["pull_number"] = context["pull_number"]
+        return row
 
 class ReviewsStream(GitHubRestStream):
     name = "reviews"
```

However, I'm not sure if this is the correct fix.

**Comment by ericboucher** [comment]
Great catch @scottmtp. Indeed, we would love a PR for this. Your change looks quite reasonable :)

**Comment by ericboucher** [comment]
@edgarrmondragon any thoughts on why this part of the context is not forwarded to the record by default? @scottmtp's change looks reasonable but I'm wondering if we should look into a higher-level fix.

**Comment by edgarrmondragon** [comment]
> @edgarrmondragon any thoughts on why this part of the context is not forwarded to the record by default? @scottmtp's change looks reasonable but I'm wondering if we should look into a higher-level fix.

@ericboucher Without diving deeper, my guess is that `state_partitioning_keys` is limiting the keys passed to `pull_requests_commits` from its parent stream.
