### ISSUE TITLE
If a member is part of multiple teams, they will only be listed once

### ISSUE THREAD

**Issue by morrislaptop** [MeltanoLabs/tap-github#190]
Since primary key only consists of the member id. 

https://github.com/MeltanoLabs/tap-github/blob/f5ce902a19a6fa6b9890f01d0d5574a18225bc55/tap_github/organization_streams.py#L126

We would need a member id / team slug combination here.

**Comment by ericboucher** [comment]
@morrislaptop thanks for flagging this. This seems quite reasonable. Could you open a small PR to fix this? Thanks.

**Comment by morrislaptop** [comment]
@ericboucher done! #204
