### ISSUE TITLE
Consider using conditional requests to check for changes

### ISSUE THREAD

**Issue by ericboucher** [MeltanoLabs/tap-github#23]
The GitHub API allows for conditional requests that do not count towards rate-limiting.

It could be interesting to leverage these and avoid making requests if they are not necessary.

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests

**Comment by aaronsteers** [comment]
@ericboucher - I did a quick review of the provided link. I can't say I fully understand the interface or intricacies here but yes, totally makes sense to take advantage of these where possible. 👍

**Comment by ericboucher** [comment]
This is only possible with endpoints that would return a "Last Modified" header and the "If-modified-since" header has to be formatted as `Wed, 04 Mar 2022 01:02:25 GMT`


See https://github.community/t/how-does-if-modified-since-work/139627
