### ISSUE TITLE
Use the GITHUB_TOKEN built-in secret for better rate limits?

### ISSUE THREAD

**Issue by aaronsteers** [MeltanoLabs/tap-github#24]
I believe as-of now, we are still limited by the no-auth rate limits, which are lower than authenticated rates.

We may get a better rate limits from using the built-in `GITHUB_TOKEN` secret. I haven't read deep enough to know if there are any specific limitations on this token which would block us, but it seems worth exploration.

https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret

**Comment by ericboucher** [comment]
Solved in #25
