### ISSUE TITLE
Add `files` property to `CommitsStream`

### ISSUE THREAD

**Issue by dlouseiro** [MeltanoLabs/tap-github#242]
I'm currently PoCing meltano as a tool to replace Fivetran.

During the comparison of data models, it was noticed that a data point was missing: the `files` property in the `Commits` stream.

This property contains details about each file changes in a commit (`# of additions`, # of deletions`, etc).

I took the liberty to open a [PR](https://github.com/MeltanoLabs/tap-github/pull/241) that should take care of extending the model.

**Comment by edgarrmondragon** [comment]
Closed by https://github.com/MeltanoLabs/tap-github/pull/241
