### ISSUE TITLE
SDK Version pointing to a specific commit

### ISSUE THREAD

**Issue by visch** [MeltanoLabs/tap-github#248]
https://github.com/MeltanoLabs/tap-github/blob/main/pyproject.toml#L33

Probably can bump this to the latest sdk version now. https://github.com/meltano/sdk/commit/c3a8f90ac4d79eb5c655740d0fd88f393af7f306 is the commit it's pointing to https://github.com/meltano/sdk/pull/1880 is the merged MR

**Comment by edgarrmondragon** [comment]
Closed by #261
