### ISSUE TITLE
Add dependents field on repositories stream

### ISSUE THREAD

**Issue by laurentS** [MeltanoLabs/tap-github#34]
We use the `dependents` count for a repository, which is currently fetched by grabbing the html page for the project (eg. https://github.com/facebook/react/network/dependents) and parsing the HTML. As I write this ticket, the link above returns `7,878,702 Repositories` (and likewise for packages) and we grab these numbers.
Unfortunately, this info does not seem to exist anywhere in either the REST or graphQL APIs.

@aaronsteers Would you have any objection to me adding a request for that page to the `repositories` stream resulting in an extra field? Possibly behind some config option as it is fairly download heavy (the page above weighs 187kB).
Maybe in the `post_process` method? Ideally, the data will eventually be available in one of the APIs, and this can then be dropped.

**Comment by ericboucher** [comment]
@laurentS I'd love to revive this now that we have the GraphQl endpoints. I think we should aim to grab both dependents and dependencies

**Comment by ericboucher** [comment]
For the dependencies, you can use this - https://docs.github.com/en/graphql/overview/schema-previews#access-to-a-repositories-dependency-graph-preview

**Comment by ericboucher** [comment]
Addressed in https://github.com/MeltanoLabs/tap-github/pull/126 and https://github.com/MeltanoLabs/tap-github/pull/127
