### ISSUE TITLE
Add `requests-cache` implementation in CI to eliminate rate limit failures

### ISSUE THREAD

**Issue by aaronsteers** [MeltanoLabs/tap-github#43]
@edgarrmondragon had an initial working implementation of requests caching using the `cached-requests` library: https://requests-cache.readthedocs.io/en/stable/

Used here: https://github.com/MeltanoLabs/tap-stackexchange/blob/main/tap_stackexchange/client.py#L7

And we have an SDK discussion on this here: https://gitlab.com/meltano/sdk/-/issues/237

@laurentS, @edgarrmondragon, and @ericboucher - If ever there were a good use case for this, I think this repo is a great one.

What do you all think of this approach?

1. When running tests in CI, invoke the `requests-cache` library to store http responses.
2. Sequence the build so that one python version is the main one (`3.9`, perhaps), and the main one runs prior to the others and stores its artifacts in a GitHub CI cache.
3. The other python versions run after the main version.
4. Even the main python version recalls the cache and thereby only has to send new requests not covered by a prior build's requests. (For instance, when a new stream is added.)

At most, this means one "main" job needs to send http requests - but in practice, even the main job should not need to make the full set of requests.

Optionally, a scheduled job could kill the cache once a week and refresh from scratch.

**Comment by laurentS** [comment]
Relates to #14 
I think the approach you suggest makes sense. I was pondering using a sort of snapshot system saved in the repo (I think vcr.py does that), but using a cache like you suggest is probably less maintenance.

Github's API rate limiting has a 1h window, after which it resets, so we could have a daily job, or even twice daily scheduled job that busts/primes the cache. I'm thinking of what would happen if github's API format suddenly changes in a way that breaks the tap, the less time we wait for CI to fail the better. If the scheduled job refreshes the caches and then runs the CI job on it, we'd get notified of failures quickly. In that case, we can even run all "regular" CI jobs from cache, so they would be much faster as well, which never hurts (and there's still the risk that 2-3 eager devs are pushing code multiple times within a 1h window and hit limits anyway :wink: )

**Comment by aaronsteers** [comment]
> I was pondering using a sort of snapshot system saved in the repo (I think vcr.py does that), but using a cache like you suggest is probably less maintenance.

I agree. In the related SDK issue, we imagine a dev lifecycle where eventually (if not in the first iteration due to PII), the caches are stored in yaml within the repo. This can power CI tests (except when we intentionally ignore/refresh the cache) gives us `--demo` behavior down the road without having to require creds that connect to the source.
