### ISSUE TITLE
Allow use cases where list of `projects` or `organizations` is already known

### ISSUE THREAD

**Issue by aaronsteers** [MeltanoLabs/tap-github#5]
Currently, this was built around the `searches` config option, which allows Github repo searches to drive dynamic repo selection.

I suggest we make three vectors for selection, each which would be mutually exclusive during setting validation:

1. `searches` - (existing) finds repos based on the search API
2. `repositories` - (hi-pri) takes a list of one or more repositories, such as `['MeltanoLabs/tap-github']`
3. `organizations` - (low-pri) takes a list of one or more organizations, such as `['MeltanoLabs']`

**Comment by laurentS** [comment]
I got started on `repositories` this afternoon (EU time).

**Comment by aaronsteers** [comment]
@laurentS - Fantastic! Thanks!

**Comment by aaronsteers** [comment]
@laurentS - Thanks for your work adding `repositories` as a top-level config setting in #7. For the organizations use case, do you think you could add one of the sample queries you shared with me into the Readme? It occured to me that we could solve this use case by simply making it straightforward on how to query for everything under a specific org - and relying on the existing search-oriented features for that use case.

What do you think?

**Comment by aaronsteers** [comment]
Closing this as resolved. Repositories is now supported as a config option, and `organizations` can be supported via a search using Github query syntax to include only the requested org(s).
