### ISSUE TITLE
Drop support for python 3.6

### ISSUE THREAD

**Issue by laurentS** [MeltanoLabs/tap-github#57]
Python 3.6 is reaching its EOL on December 23rd, so this is probably a good time to drop support for it.
Any objections to a short PR dropping 3.6 from CI and `pyproject.toml`?

Source: https://endoflife.date/python

**Comment by edgarrmondragon** [comment]
@laurentS No objections from me 👍 

cc @aaronsteers

**Comment by aaronsteers** [comment]
@laurentS - Agreed!
