### ISSUE TITLE
Reactions +1 and -1 field names cause downstream issues

### ISSUE THREAD

**Issue by JohannesRudolph** [MeltanoLabs/tap-github#64]
I'm trying to load this tap-github into target-bigquery and get the following error

```text
CRITICAL Duplicate field(s) in stream issues:          & reactions.-1 are read as REACTIONS._1 by BigQuery
```

The `pull_requests` stream has the same problem. What's the best way to deal with it? Having the special chars +/- in the schema name causes trouble, should this be fixed at the extractor level or should I look for a solution with this particular loader?

**Comment by ericboucher** [comment]
Hi @JohannesRudolph, thanks for opening this issue! We will look into renaming these fields.

Another option would be to handle that in the loader and have a parser that handles this a bit better. Can you link the bigquery loader here for reference?

**Comment by JohannesRudolph** [comment]
Sure, I'm using [adswerve/target-bigquery](https://github.com/adswerve/target-bigquery)

**Comment by ericboucher** [comment]
@JohannesRudolph I opened https://github.com/adswerve/target-bigquery/pull/29 which should solve your issue. Hopefully they merge it quickly but feel free to use it as is of course.

**Comment by laurentS** [comment]
We actually have a similar, though slightly different, issue with `target-postgres` which issues the following warnings on these fields:
```
INFO Table Schema Change [`pull_requests`.`('reactions', '+1')`:`reactions___1`] New column (took 2 millis)
WARNING NAME COLLISION: Field `('reactions', '-1')` collided with `reactions___1` in remote. Adding new integer suffix...
INFO Table Schema Change [`pull_requests`.`('reactions', '-1')`:`reactions___1__1`] New column (took 2 millis)
```

I suspect a bunch of other targets might have variants of this problem as they map the characters. Maybe we should consider renaming the fields in the tap for consistency?
- `reactions_plus_1`
- `reactions_minus_1`
